// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dzhbus.proto

#ifndef PROTOBUF_dzhbus_2eproto__INCLUDED
#define PROTOBUF_dzhbus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dzhyun {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_dzhbus_2eproto();
void protobuf_AssignDesc_dzhbus_2eproto();
void protobuf_ShutdownFile_dzhbus_2eproto();

class BusHead;
class RspInfo;
class AnyReq;
class LoginRsp;
class LogoutRsp;

// ===================================================================

class BusHead : public ::google::protobuf::Message {
 public:
  BusHead();
  virtual ~BusHead();

  BusHead(const BusHead& from);

  inline BusHead& operator=(const BusHead& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const BusHead& default_instance();

  void Swap(BusHead* other);

  // implements Message ----------------------------------------------

  BusHead* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BusHead& from);
  void MergeFrom(const BusHead& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint64 RequestID = 1;
  inline bool has_requestid() const;
  inline void clear_requestid();
  static const int kRequestIDFieldNumber = 1;
  inline ::google::protobuf::uint64 requestid() const;
  inline void set_requestid(::google::protobuf::uint64 value);

  // required string ServiceName = 2;
  inline bool has_servicename() const;
  inline void clear_servicename();
  static const int kServiceNameFieldNumber = 2;
  inline const ::std::string& servicename() const;
  inline void set_servicename(const ::std::string& value);
  inline void set_servicename(const char* value);
  inline void set_servicename(const char* value, size_t size);
  inline ::std::string* mutable_servicename();
  inline ::std::string* release_servicename();
  inline void set_allocated_servicename(::std::string* servicename);

  // optional bytes Data = 3;
  inline bool has_data() const;
  inline void clear_data();
  static const int kDataFieldNumber = 3;
  inline const ::std::string& data() const;
  inline void set_data(const ::std::string& value);
  inline void set_data(const char* value);
  inline void set_data(const void* value, size_t size);
  inline ::std::string* mutable_data();
  inline ::std::string* release_data();
  inline void set_allocated_data(::std::string* data);

  // optional uint32 EndFlag = 4;
  inline bool has_endflag() const;
  inline void clear_endflag();
  static const int kEndFlagFieldNumber = 4;
  inline ::google::protobuf::uint32 endflag() const;
  inline void set_endflag(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:dzhyun.BusHead)
 private:
  inline void set_has_requestid();
  inline void clear_has_requestid();
  inline void set_has_servicename();
  inline void clear_has_servicename();
  inline void set_has_data();
  inline void clear_has_data();
  inline void set_has_endflag();
  inline void clear_has_endflag();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint64 requestid_;
  ::std::string* servicename_;
  ::std::string* data_;
  ::google::protobuf::uint32 endflag_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_dzhbus_2eproto();
  friend void protobuf_AssignDesc_dzhbus_2eproto();
  friend void protobuf_ShutdownFile_dzhbus_2eproto();

  void InitAsDefaultInstance();
  static BusHead* default_instance_;
};
// -------------------------------------------------------------------

class RspInfo : public ::google::protobuf::Message {
 public:
  RspInfo();
  virtual ~RspInfo();

  RspInfo(const RspInfo& from);

  inline RspInfo& operator=(const RspInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RspInfo& default_instance();

  void Swap(RspInfo* other);

  // implements Message ----------------------------------------------

  RspInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RspInfo& from);
  void MergeFrom(const RspInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 RspNo = 1;
  inline bool has_rspno() const;
  inline void clear_rspno();
  static const int kRspNoFieldNumber = 1;
  inline ::google::protobuf::uint32 rspno() const;
  inline void set_rspno(::google::protobuf::uint32 value);

  // optional string RspDesc = 2;
  inline bool has_rspdesc() const;
  inline void clear_rspdesc();
  static const int kRspDescFieldNumber = 2;
  inline const ::std::string& rspdesc() const;
  inline void set_rspdesc(const ::std::string& value);
  inline void set_rspdesc(const char* value);
  inline void set_rspdesc(const char* value, size_t size);
  inline ::std::string* mutable_rspdesc();
  inline ::std::string* release_rspdesc();
  inline void set_allocated_rspdesc(::std::string* rspdesc);

  // @@protoc_insertion_point(class_scope:dzhyun.RspInfo)
 private:
  inline void set_has_rspno();
  inline void clear_has_rspno();
  inline void set_has_rspdesc();
  inline void clear_has_rspdesc();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* rspdesc_;
  ::google::protobuf::uint32 rspno_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_dzhbus_2eproto();
  friend void protobuf_AssignDesc_dzhbus_2eproto();
  friend void protobuf_ShutdownFile_dzhbus_2eproto();

  void InitAsDefaultInstance();
  static RspInfo* default_instance_;
};
// -------------------------------------------------------------------

class AnyReq : public ::google::protobuf::Message {
 public:
  AnyReq();
  virtual ~AnyReq();

  AnyReq(const AnyReq& from);

  inline AnyReq& operator=(const AnyReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AnyReq& default_instance();

  void Swap(AnyReq* other);

  // implements Message ----------------------------------------------

  AnyReq* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AnyReq& from);
  void MergeFrom(const AnyReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Url = 1;
  inline bool has_url() const;
  inline void clear_url();
  static const int kUrlFieldNumber = 1;
  inline const ::std::string& url() const;
  inline void set_url(const ::std::string& value);
  inline void set_url(const char* value);
  inline void set_url(const char* value, size_t size);
  inline ::std::string* mutable_url();
  inline ::std::string* release_url();
  inline void set_allocated_url(::std::string* url);

  // @@protoc_insertion_point(class_scope:dzhyun.AnyReq)
 private:
  inline void set_has_url();
  inline void clear_has_url();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* url_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_dzhbus_2eproto();
  friend void protobuf_AssignDesc_dzhbus_2eproto();
  friend void protobuf_ShutdownFile_dzhbus_2eproto();

  void InitAsDefaultInstance();
  static AnyReq* default_instance_;
};
// -------------------------------------------------------------------

class LoginRsp : public ::google::protobuf::Message {
 public:
  LoginRsp();
  virtual ~LoginRsp();

  LoginRsp(const LoginRsp& from);

  inline LoginRsp& operator=(const LoginRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LoginRsp& default_instance();

  void Swap(LoginRsp* other);

  // implements Message ----------------------------------------------

  LoginRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LoginRsp& from);
  void MergeFrom(const LoginRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .dzhyun.RspInfo rspInfo = 1;
  inline bool has_rspinfo() const;
  inline void clear_rspinfo();
  static const int kRspInfoFieldNumber = 1;
  inline const ::dzhyun::RspInfo& rspinfo() const;
  inline ::dzhyun::RspInfo* mutable_rspinfo();
  inline ::dzhyun::RspInfo* release_rspinfo();
  inline void set_allocated_rspinfo(::dzhyun::RspInfo* rspinfo);

  // @@protoc_insertion_point(class_scope:dzhyun.LoginRsp)
 private:
  inline void set_has_rspinfo();
  inline void clear_has_rspinfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::dzhyun::RspInfo* rspinfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_dzhbus_2eproto();
  friend void protobuf_AssignDesc_dzhbus_2eproto();
  friend void protobuf_ShutdownFile_dzhbus_2eproto();

  void InitAsDefaultInstance();
  static LoginRsp* default_instance_;
};
// -------------------------------------------------------------------

class LogoutRsp : public ::google::protobuf::Message {
 public:
  LogoutRsp();
  virtual ~LogoutRsp();

  LogoutRsp(const LogoutRsp& from);

  inline LogoutRsp& operator=(const LogoutRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LogoutRsp& default_instance();

  void Swap(LogoutRsp* other);

  // implements Message ----------------------------------------------

  LogoutRsp* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LogoutRsp& from);
  void MergeFrom(const LogoutRsp& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required .dzhyun.RspInfo rspInfo = 1;
  inline bool has_rspinfo() const;
  inline void clear_rspinfo();
  static const int kRspInfoFieldNumber = 1;
  inline const ::dzhyun::RspInfo& rspinfo() const;
  inline ::dzhyun::RspInfo* mutable_rspinfo();
  inline ::dzhyun::RspInfo* release_rspinfo();
  inline void set_allocated_rspinfo(::dzhyun::RspInfo* rspinfo);

  // @@protoc_insertion_point(class_scope:dzhyun.LogoutRsp)
 private:
  inline void set_has_rspinfo();
  inline void clear_has_rspinfo();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::dzhyun::RspInfo* rspinfo_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_dzhbus_2eproto();
  friend void protobuf_AssignDesc_dzhbus_2eproto();
  friend void protobuf_ShutdownFile_dzhbus_2eproto();

  void InitAsDefaultInstance();
  static LogoutRsp* default_instance_;
};
// ===================================================================


// ===================================================================

// BusHead

// required uint64 RequestID = 1;
inline bool BusHead::has_requestid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BusHead::set_has_requestid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BusHead::clear_has_requestid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BusHead::clear_requestid() {
  requestid_ = GOOGLE_ULONGLONG(0);
  clear_has_requestid();
}
inline ::google::protobuf::uint64 BusHead::requestid() const {
  return requestid_;
}
inline void BusHead::set_requestid(::google::protobuf::uint64 value) {
  set_has_requestid();
  requestid_ = value;
}

// required string ServiceName = 2;
inline bool BusHead::has_servicename() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BusHead::set_has_servicename() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BusHead::clear_has_servicename() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BusHead::clear_servicename() {
  if (servicename_ != &::google::protobuf::internal::kEmptyString) {
    servicename_->clear();
  }
  clear_has_servicename();
}
inline const ::std::string& BusHead::servicename() const {
  return *servicename_;
}
inline void BusHead::set_servicename(const ::std::string& value) {
  set_has_servicename();
  if (servicename_ == &::google::protobuf::internal::kEmptyString) {
    servicename_ = new ::std::string;
  }
  servicename_->assign(value);
}
inline void BusHead::set_servicename(const char* value) {
  set_has_servicename();
  if (servicename_ == &::google::protobuf::internal::kEmptyString) {
    servicename_ = new ::std::string;
  }
  servicename_->assign(value);
}
inline void BusHead::set_servicename(const char* value, size_t size) {
  set_has_servicename();
  if (servicename_ == &::google::protobuf::internal::kEmptyString) {
    servicename_ = new ::std::string;
  }
  servicename_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BusHead::mutable_servicename() {
  set_has_servicename();
  if (servicename_ == &::google::protobuf::internal::kEmptyString) {
    servicename_ = new ::std::string;
  }
  return servicename_;
}
inline ::std::string* BusHead::release_servicename() {
  clear_has_servicename();
  if (servicename_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = servicename_;
    servicename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BusHead::set_allocated_servicename(::std::string* servicename) {
  if (servicename_ != &::google::protobuf::internal::kEmptyString) {
    delete servicename_;
  }
  if (servicename) {
    set_has_servicename();
    servicename_ = servicename;
  } else {
    clear_has_servicename();
    servicename_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes Data = 3;
inline bool BusHead::has_data() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BusHead::set_has_data() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BusHead::clear_has_data() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BusHead::clear_data() {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    data_->clear();
  }
  clear_has_data();
}
inline const ::std::string& BusHead::data() const {
  return *data_;
}
inline void BusHead::set_data(const ::std::string& value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void BusHead::set_data(const char* value) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(value);
}
inline void BusHead::set_data(const void* value, size_t size) {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  data_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BusHead::mutable_data() {
  set_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    data_ = new ::std::string;
  }
  return data_;
}
inline ::std::string* BusHead::release_data() {
  clear_has_data();
  if (data_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = data_;
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void BusHead::set_allocated_data(::std::string* data) {
  if (data_ != &::google::protobuf::internal::kEmptyString) {
    delete data_;
  }
  if (data) {
    set_has_data();
    data_ = data;
  } else {
    clear_has_data();
    data_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional uint32 EndFlag = 4;
inline bool BusHead::has_endflag() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BusHead::set_has_endflag() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BusHead::clear_has_endflag() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BusHead::clear_endflag() {
  endflag_ = 0u;
  clear_has_endflag();
}
inline ::google::protobuf::uint32 BusHead::endflag() const {
  return endflag_;
}
inline void BusHead::set_endflag(::google::protobuf::uint32 value) {
  set_has_endflag();
  endflag_ = value;
}

// -------------------------------------------------------------------

// RspInfo

// required uint32 RspNo = 1;
inline bool RspInfo::has_rspno() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RspInfo::set_has_rspno() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RspInfo::clear_has_rspno() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RspInfo::clear_rspno() {
  rspno_ = 0u;
  clear_has_rspno();
}
inline ::google::protobuf::uint32 RspInfo::rspno() const {
  return rspno_;
}
inline void RspInfo::set_rspno(::google::protobuf::uint32 value) {
  set_has_rspno();
  rspno_ = value;
}

// optional string RspDesc = 2;
inline bool RspInfo::has_rspdesc() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RspInfo::set_has_rspdesc() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RspInfo::clear_has_rspdesc() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RspInfo::clear_rspdesc() {
  if (rspdesc_ != &::google::protobuf::internal::kEmptyString) {
    rspdesc_->clear();
  }
  clear_has_rspdesc();
}
inline const ::std::string& RspInfo::rspdesc() const {
  return *rspdesc_;
}
inline void RspInfo::set_rspdesc(const ::std::string& value) {
  set_has_rspdesc();
  if (rspdesc_ == &::google::protobuf::internal::kEmptyString) {
    rspdesc_ = new ::std::string;
  }
  rspdesc_->assign(value);
}
inline void RspInfo::set_rspdesc(const char* value) {
  set_has_rspdesc();
  if (rspdesc_ == &::google::protobuf::internal::kEmptyString) {
    rspdesc_ = new ::std::string;
  }
  rspdesc_->assign(value);
}
inline void RspInfo::set_rspdesc(const char* value, size_t size) {
  set_has_rspdesc();
  if (rspdesc_ == &::google::protobuf::internal::kEmptyString) {
    rspdesc_ = new ::std::string;
  }
  rspdesc_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RspInfo::mutable_rspdesc() {
  set_has_rspdesc();
  if (rspdesc_ == &::google::protobuf::internal::kEmptyString) {
    rspdesc_ = new ::std::string;
  }
  return rspdesc_;
}
inline ::std::string* RspInfo::release_rspdesc() {
  clear_has_rspdesc();
  if (rspdesc_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = rspdesc_;
    rspdesc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RspInfo::set_allocated_rspdesc(::std::string* rspdesc) {
  if (rspdesc_ != &::google::protobuf::internal::kEmptyString) {
    delete rspdesc_;
  }
  if (rspdesc) {
    set_has_rspdesc();
    rspdesc_ = rspdesc;
  } else {
    clear_has_rspdesc();
    rspdesc_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// AnyReq

// required string Url = 1;
inline bool AnyReq::has_url() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AnyReq::set_has_url() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AnyReq::clear_has_url() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AnyReq::clear_url() {
  if (url_ != &::google::protobuf::internal::kEmptyString) {
    url_->clear();
  }
  clear_has_url();
}
inline const ::std::string& AnyReq::url() const {
  return *url_;
}
inline void AnyReq::set_url(const ::std::string& value) {
  set_has_url();
  if (url_ == &::google::protobuf::internal::kEmptyString) {
    url_ = new ::std::string;
  }
  url_->assign(value);
}
inline void AnyReq::set_url(const char* value) {
  set_has_url();
  if (url_ == &::google::protobuf::internal::kEmptyString) {
    url_ = new ::std::string;
  }
  url_->assign(value);
}
inline void AnyReq::set_url(const char* value, size_t size) {
  set_has_url();
  if (url_ == &::google::protobuf::internal::kEmptyString) {
    url_ = new ::std::string;
  }
  url_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* AnyReq::mutable_url() {
  set_has_url();
  if (url_ == &::google::protobuf::internal::kEmptyString) {
    url_ = new ::std::string;
  }
  return url_;
}
inline ::std::string* AnyReq::release_url() {
  clear_has_url();
  if (url_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = url_;
    url_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void AnyReq::set_allocated_url(::std::string* url) {
  if (url_ != &::google::protobuf::internal::kEmptyString) {
    delete url_;
  }
  if (url) {
    set_has_url();
    url_ = url;
  } else {
    clear_has_url();
    url_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// LoginRsp

// required .dzhyun.RspInfo rspInfo = 1;
inline bool LoginRsp::has_rspinfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LoginRsp::set_has_rspinfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LoginRsp::clear_has_rspinfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LoginRsp::clear_rspinfo() {
  if (rspinfo_ != NULL) rspinfo_->::dzhyun::RspInfo::Clear();
  clear_has_rspinfo();
}
inline const ::dzhyun::RspInfo& LoginRsp::rspinfo() const {
  return rspinfo_ != NULL ? *rspinfo_ : *default_instance_->rspinfo_;
}
inline ::dzhyun::RspInfo* LoginRsp::mutable_rspinfo() {
  set_has_rspinfo();
  if (rspinfo_ == NULL) rspinfo_ = new ::dzhyun::RspInfo;
  return rspinfo_;
}
inline ::dzhyun::RspInfo* LoginRsp::release_rspinfo() {
  clear_has_rspinfo();
  ::dzhyun::RspInfo* temp = rspinfo_;
  rspinfo_ = NULL;
  return temp;
}
inline void LoginRsp::set_allocated_rspinfo(::dzhyun::RspInfo* rspinfo) {
  delete rspinfo_;
  rspinfo_ = rspinfo;
  if (rspinfo) {
    set_has_rspinfo();
  } else {
    clear_has_rspinfo();
  }
}

// -------------------------------------------------------------------

// LogoutRsp

// required .dzhyun.RspInfo rspInfo = 1;
inline bool LogoutRsp::has_rspinfo() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LogoutRsp::set_has_rspinfo() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LogoutRsp::clear_has_rspinfo() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LogoutRsp::clear_rspinfo() {
  if (rspinfo_ != NULL) rspinfo_->::dzhyun::RspInfo::Clear();
  clear_has_rspinfo();
}
inline const ::dzhyun::RspInfo& LogoutRsp::rspinfo() const {
  return rspinfo_ != NULL ? *rspinfo_ : *default_instance_->rspinfo_;
}
inline ::dzhyun::RspInfo* LogoutRsp::mutable_rspinfo() {
  set_has_rspinfo();
  if (rspinfo_ == NULL) rspinfo_ = new ::dzhyun::RspInfo;
  return rspinfo_;
}
inline ::dzhyun::RspInfo* LogoutRsp::release_rspinfo() {
  clear_has_rspinfo();
  ::dzhyun::RspInfo* temp = rspinfo_;
  rspinfo_ = NULL;
  return temp;
}
inline void LogoutRsp::set_allocated_rspinfo(::dzhyun::RspInfo* rspinfo) {
  delete rspinfo_;
  rspinfo_ = rspinfo;
  if (rspinfo) {
    set_has_rspinfo();
  } else {
    clear_has_rspinfo();
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dzhyun

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_dzhbus_2eproto__INCLUDED
